In [3]:
import numpy as np
mylist = [1,2,3]
myarray =np.array(mylist)
print(myarray)
print(myarray.shape)

[1 2 3]
(3,)


In [7]:
mylist = [[1,2,3],[3,4,5]]
myarray = np.array(mylist)
print(myarray)
print(myarray.shape)
print("Firat row: %s" % myarray[0])
print("Last row: %s" % myarray[-1])
print("Specific row and col: %s" % myarray[0,1])
print("Whole col: %s" % myarray[:,2])

[[1 2 3]
 [3 4 5]]
(2, 3)
Firat row: [1 2 3]
Last row: [3 4 5]
Specific row and col: 2
Whole col: [3 5]


In [9]:
## Arithmatic

myarray1 = np.array([2,2,2])
myarray2 = np.array([3,3,3])

print("Addition: %s" % (myarray1 + myarray2))
print("Multiplecation: %s" % (myarray1 * myarray2))

Addition: [5 5 5]
Multiplecation: [6 6 6]
